@startuml ClassDesign

left to right direction

skinparam backgroundColor #DAFAF3FF

package Manikin_Software {
    class BreathingControl {
        Description:
        This class will Breathingcontrol
        the CompressionClass and the BreathingClass
        according to the logic input.
        The logical input will be 
        chosen according to the measured 
        values from the sensors
    }

    class Compression {
        Description:
        This class will have the Breathingcontrol
        of the motor that will make the 
        Compression moving. The pattern off the
        movement will be chosen from the BreathingControlClass
    }

    class Breathing {
        Description:
        This class Uses the incoming datapoints
        to Breathingcontrol the Compression Compression with the Motor class
    }
}

package Manikin_Software_Libraries {
    namespace Actuators {
        class Motor {
            Description:
            This class will Breathingcontrol the motor
            that should move the Compression of the
            baby. The class will get input from
            the CompressionClass to make certain 
            CompressionMovements
        }

        class Pump {
            Description:
            This class wil Breathingcontrol the pump
            that should pump the air outside 
            the nose of the baby with a 
            certine speed. The class will get
            input from the ...Class to determine 
            the pattern of the airPonmbing 
        }
    }
    namespace I2C {
        class I2CDriver {
            Description:
            Base class for I2C protocol
        }

        class BreathingModuleI2C {
            Description:
            Class used for in the BreathingModule for communication to the main board,
            This data includes:
            "- A start signal"
            "- A stop signal"
            "- (optional) A datastream for different breathing patterns"            
        }

        BreathingModuleI2C <|-- I2CDriver
    }
}

I2C.BreathingModuleI2C --* BreathingControl 
BreathingControl o-- Compression : Pattern of Compressionmovements
BreathingControl o-- Breathing : Pattern of AirPumping
Compression   *-- Actuators.Motor : BreathingControl MotorCompression according to received pattern
Breathing *-- Actuators.Pump : BreathingControl Pump according to received pattern

@enduml